### ISSUE TITLE
4.0.1 does not ship with `.d.ts` file

### ISSUE THREAD

**Issue by samueljseay** [aduth/rememo#11]
I noticed that TypeScript type definitions break for us if we upgrade to 4.0.1 it seems because the `.d.ts` file was not shipped with the release.

**Comment by aduth** [comment]
Thanks for flagging this, @samueljseay . The `.d.ts` file was included in the v4.0.1 release, but it wasn't being resolved automatically by TypeScript, perhaps due to how the package includes both a CommonJS and native ES Module versions.

I believe this should now be fixed in the v4.0.2 release I just published. Can you give it a try and let me know if you're still having issues?
