### ISSUE TITLE
Add TypeScript type definition

### ISSUE THREAD

**Issue by ocean90** [aduth/rememo#2]
I'm wondering if you're interested in adding typings to the library, similar to https://github.com/aduth/memize/commit/3a6f1cd38e25cf37716d2398c6ab098992acccfb?

**Comment by aduth** [comment]
I'd be interested, sure. I hadn't had a chance (or the motivation) to implement it here yet.

**Comment by aduth** [comment]
Just a small update: I'd started to try to add these type definitions. I've found it a bit more difficult to implement than I'd anticipated, partly because the optional WeakMap support (and duck-typing therein) is difficult to reconcile with strong typing.

I have a work-in-progress branch here: https://github.com/aduth/rememo/compare/add-typescript

A possible compromise solution could be to at least add a definitions file for the public API of the default export, if even that means internally the project isn't fully type-checked.

**Comment by mdmag** [comment]
@aduth Thanks for this great work! This package helped me a lot in my project to memoize my selectors and the performance is really optimized but I have issues with the package once I decided to turn my project to Typescript. I hope this package would support typescript. This would definitely help!

**Comment by mdmag** [comment]
> A possible compromise solution could be to at least add a definitions file for the public API of the default export, if even that means internally the project isn't fully type-checked.

I fully agree with that. That would be enough. I tried to turn the package into TS  but I found the same problems you mentioned about the WeakMap and how it is difficult to reconcile with strong typing.

**Comment by mdmag** [comment]
@aduth I handled this by having custom type declaration file: https://github.com/QuillForms/QuillForms/blob/master/typings/rememo/index.d.ts

**Comment by aduth** [comment]
@mdmag Thanks for the nudge here, and apologies for sitting on it so long.

To my last update, the direction I'm planning is to drop support for environments which don't have WeakMap. I think I assumed Internet Explorer didn't support it, but it has good enough support.

This made adding the types a bit more straightforward, implemented in e849904.

I've a few other changes I'm working on, but hoping to publish a new version tomorrow.

**Comment by aduth** [comment]
v4.0.0 is now published 🚀
